configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepg99999438acr.azurecr.io/cloud-sample-99999438
  newTag: "202410020219"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202408120727"
