spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cepg-99999438-postgres.private.postgres.database.azure.com:3306/postgres
    username: postgres
    password: cepg1234

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
